Fix indent

diff --git a/.github/workflows/PR_Trigger.yml b/.github/workflows/PR_Trigger.yml
--- a/.github/workflows/PR_Trigger.yml
+++ b/.github/workflows/PR_Trigger.yml
@@ -7,38 +7,38 @@ on:
 jobs:
   # This particular job was inspired by https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-issue-labels-to-pr.yml
   Add-Linked-Issue-Labels-To-PR:
-  runs-on: ubuntu-latest
-  if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'edited') }}
-  steps:
-    # Gets the linked issue from the PR body
-    - name: Retrieve Linked Issue From PR
-      uses: actions/github-script@v4
-      uses: actions/github-script@v4
-      id: linked-issue
-      with:
-        script: |
-          const script = require('./.github/js/add-linked-issue-labels-to-pr/main.js')
-          const issueNum = script({ g: github, c: context })
-          return issueNum
-    
-    # Returns loudly if previous step failed
-    - name: Return Failure
-      if: ${{ steps.linked-issue.result == 'false' }}
-      run: |
-        echo "Please expand above outputs for errors."
-        exit 1
-    
-    # Create an artifact with the results
-    - name: Create Artifacts
-      # Escapes user input for injection attacks
-      env:
-        ARTIFACT: ${{ steps.linked-issue.outputs.result }}
-      run: |
-        mkdir -p addingLabelsAction/artifact
-        echo ${{ env.ARTIFACT }} > addingLabelsAction/artifact/artifact.txt
-          
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v2
-      with:
-        name: adding-labels-action-artifact
-        path: addingLabelsAction/artifact/
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'edited') }}
+    steps:
+      # Gets the linked issue from the PR body
+      - name: Retrieve Linked Issue From PR
+        uses: actions/github-script@v4
+        uses: actions/github-script@v4
+        id: linked-issue
+        with:
+          script: |
+            const script = require('./.github/js/add-linked-issue-labels-to-pr/main.js')
+            const issueNum = script({ g: github, c: context })
+            return issueNum
+      
+      # Returns loudly if previous step failed
+      - name: Return Failure
+        if: ${{ steps.linked-issue.result == 'false' }}
+        run: |
+          echo "Please expand above outputs for errors."
+          exit 1
+      
+      # Create an artifact with the results
+      - name: Create Artifacts
+        # Escapes user input for injection attacks
+        env:
+          ARTIFACT: ${{ steps.linked-issue.outputs.result }}
+        run: |
+          mkdir -p addingLabelsAction/artifact
+          echo ${{ env.ARTIFACT }} > addingLabelsAction/artifact/artifact.txt
+            
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: adding-labels-action-artifact
+          path: addingLabelsAction/artifact/
